# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  metrics-api:
    type: string
    default: '/metrics'
    description: metrics api route
  metrics-scrape-interval:
    type: string
    default: '30s'
    description: how often metrics are scraped
  metrics-port:
    type: string
    default: '8080'
    description: Metrics port
